[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 200
solc = "0.8.23"

[fuzz]
runs = 5_000

[profile.ci]
verbosity = 4
