[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/invariant'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 200
solc = "0.8.23"

[fuzz]
runs = 5_000

[invariant]
runs = 100
depth = 60
fail_on_revert = false

[profile.ci]
verbosity = 4
