const SENIOR_TRANCHE = 0;
const JUNIOR_TRANCHE = 1;
const BORROWER_LOSS_COVER_INDEX = 0;
const ADMIN_LOSS_COVER_INDEX = 2;

export const CONSTANTS = {
    SENIOR_TRANCHE,
    JUNIOR_TRANCHE,
    BORROWER_LOSS_COVER_INDEX,
    ADMIN_LOSS_COVER_INDEX,
};
