name: CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: ["main", "develop", "release*"]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Lint contracts
        run: yarn lint-solidity
      - name: Lint tests
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test  --typecheck
